# Generated by Django 5.2.10 on 2026-02-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100, unique=True)),
                ("user_email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
